name: C++ CI

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build CMake project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.26.4'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build --config Release